#include "instructions.h"
#include "sm83.h"

// clang-format off
Instruction instructions[] = {
    {{nop}, {}},
    {{ld_rr_nn_m0, ld_rr_nn_m1, ld_rr_nn_m2}, {{.reg16 = REG16_BC}}},
    {{ld_bc_a_m0, ld_bc_a_m1}, {}},
    {{inc_rr_m0, inc_rr_m1}, {{.reg16 = REG16_BC}}},
    {{inc_r}, {{.reg8 = REG8_B}}},
    {{dec_r}, {{.reg8 = REG8_B}}},
    {{ld_r_n_m0, ld_r_n_m1}, {{.reg8 = REG8_B}}},
    {{rlca}, {}},
    {{ld_nn_sp_m0, ld_nn_sp_m1, ld_nn_sp_m2, ld_nn_sp_m3, ld_nn_sp_m4}, {}},
    {{add_hl_rr_m0, add_hl_rr_m1}, {{.reg16 = REG16_BC}}},
    {{ld_a_bc_m0, ld_a_bc_m1}, {}},
    {{dec_rr_m0, dec_rr_m1}, {{.reg16 = REG16_BC}}},
    {{inc_r}, {{.reg8 = REG8_C}}},
    {{dec_r}, {{.reg8 = REG8_C}}},
    {{ld_r_n_m0, ld_r_n_m1}, {{.reg8 = REG8_C}}},
    {{rrca}, {}},
    {{stop}, {}},
    {{ld_rr_nn_m0, ld_rr_nn_m1, ld_rr_nn_m2}, {{.reg16 = REG16_DE}}},
    {{ld_de_a_m0, ld_de_a_m1}, {}},
    {{inc_rr_m0, inc_rr_m1}, {{.reg16 = REG16_DE}}},
    {{inc_r}, {{.reg8 = REG8_D}}},
    {{dec_r}, {{.reg8 = REG8_D}}},
    {{ld_r_n_m0, ld_r_n_m1}, {{.reg8 = REG8_D}}},
    {{rla}, {}},
    {{jr_e_m0, jr_e_m1, jr_e_m2}, {}},
    {{add_hl_rr_m0, add_hl_rr_m1}, {{.reg16 = REG16_DE}}},
    {{ld_a_de_m0, ld_a_de_m1}, {}},
    {{dec_rr_m0, dec_rr_m1}, {{.reg16 = REG16_DE}}},
    {{inc_r}, {{.reg8 = REG8_E}}},
    {{dec_r}, {{.reg8 = REG8_E}}},
    {{ld_r_n_m0, ld_r_n_m1}, {{.reg8 = REG8_E}}},
    {{rra}, {}},
    {{jr_ncc_e_m0, jr_ncc_e_m1, jr_ncc_e_m2}, {{.flags = ZERO_FLAG}}},
    {{ld_rr_nn_m0, ld_rr_nn_m1, ld_rr_nn_m2}, {{.reg16 = REG16_HL}}},
    {{ldi_hl_a_m0, ldi_hl_a_m1}, {}},
    {{inc_rr_m0, inc_rr_m1}, {{.reg16 = REG16_HL}}},
    {{inc_r}, {{.reg8 = REG8_H}}},
    {{dec_r}, {{.reg8 = REG8_H}}},
    {{ld_r_n_m0, ld_r_n_m1}, {{.reg8 = REG8_H}}},
    {{daa}, {}},
    {{jr_cc_e_m0, jr_cc_e_m1, jr_cc_e_m2}, {{.flags = ZERO_FLAG}}},
    {{add_hl_rr_m0, add_hl_rr_m1}, {{.reg16 = REG16_HL}}},
    {{ldi_a_hl_m0, ldi_a_hl_m1}, {}},
    {{dec_rr_m0, dec_rr_m1}, {{.reg16 = REG16_HL}}},
    {{inc_r}, {{.reg8 = REG8_L}}},
    {{dec_r}, {{.reg8 = REG8_L}}},
    {{ld_r_n_m0, ld_r_n_m1}, {{.reg8 = REG8_L}}},
    {{cpl}, {}},
    {{jr_ncc_e_m0, jr_ncc_e_m1, jr_ncc_e_m2}, {{.flags = CARRY_FLAG}}},
    {{ld_rr_nn_m0, ld_rr_nn_m1, ld_rr_nn_m2}, {{.reg16 = REG16_SP}}},
    {{ldd_hl_a_m0, ldd_hl_a_m1}, {}},
    {{inc_rr_m0, inc_rr_m1}, {{.reg16 = REG16_SP}}},
    {{inc_hl_m0, inc_hl_m1, inc_hl_m2}, {{.reg16 = REG16_HL}}},
    {{dec_hl_m0, dec_hl_m1, dec_hl_m2}, {{.reg16 = REG16_HL}}},
    {{ld_hl_n_m0, ld_hl_n_m1, ld_hl_n_m2}, {{.reg16 = REG16_HL}}},
    {{scf}, {}},
    {{jr_cc_e_m0, jr_cc_e_m1, jr_cc_e_m2}, {{.flags = CARRY_FLAG}}},
    {{add_hl_rr_m0, add_hl_rr_m1}, {{.reg16 = REG16_SP}}},
    {{ldd_a_hl_m0, ldd_a_hl_m1}, {}},
    {{dec_rr_m0, dec_rr_m1}, {{.reg16 = REG16_SP}}},
    {{inc_r}, {{.reg8 = REG8_A}}},
    {{dec_r}, {{.reg8 = REG8_A}}},
    {{ld_r_n_m0, ld_r_n_m1}, {{.reg8 = REG8_A}}},
    {{ccf}, {}},
    {{ld_r_rp}, {{.reg8 = REG8_B},  {.reg8 = REG8_B}}},
    {{ld_r_rp}, {{.reg8 = REG8_B}, {.reg8 = REG8_C}}},
    {{ld_r_rp}, {{.reg8 = REG8_B}, {.reg8 = REG8_D}}},
    {{ld_r_rp}, {{.reg8 = REG8_B}, {.reg8 = REG8_E}}},
    {{ld_r_rp}, {{.reg8 = REG8_B}, {.reg8 = REG8_H}}},
    {{ld_r_rp}, {{.reg8 = REG8_B}, {.reg8 = REG8_L}}},
    {{ld_r_hl_m0, ld_r_hl_m1}, {{.reg8 = REG8_B}}},
    {{ld_r_rp}, {{.reg8 = REG8_B}, {.reg8 = REG8_A}}},
    {{ld_r_rp}, {{.reg8 = REG8_C}, {.reg8 = REG8_B}}},
    {{ld_r_rp}, {{.reg8 = REG8_C}, {.reg8 = REG8_C}}},
    {{ld_r_rp}, {{.reg8 = REG8_C}, {.reg8 = REG8_D}}},
    {{ld_r_rp}, {{.reg8 = REG8_C}, {.reg8 = REG8_E}}},
    {{ld_r_rp}, {{.reg8 = REG8_C}, {.reg8 = REG8_H}}},
    {{ld_r_rp}, {{.reg8 = REG8_C}, {.reg8 = REG8_L}}},
    {{ld_r_hl_m0, ld_r_hl_m1}, {{.reg8 = REG8_C}}},
    {{ld_r_rp}, {{.reg8 = REG8_C}, {.reg8 = REG8_A}}},
    {{ld_r_rp}, {{.reg8 = REG8_D}, {.reg8 = REG8_B}}},
    {{ld_r_rp}, {{.reg8 = REG8_D}, {.reg8 = REG8_C}}},
    {{ld_r_rp}, {{.reg8 = REG8_D}, {.reg8 = REG8_D}}},
    {{ld_r_rp}, {{.reg8 = REG8_D}, {.reg8 = REG8_E}}},
    {{ld_r_rp}, {{.reg8 = REG8_D}, {.reg8 = REG8_H}}},
    {{ld_r_rp}, {{.reg8 = REG8_D}, {.reg8 = REG8_L}}},
    {{ld_r_hl_m0, ld_r_hl_m1}, {{.reg8 = REG8_D}}},
    {{ld_r_rp}, {{.reg8 = REG8_D}, {.reg8 = REG8_A}}},
    {{ld_r_rp}, {{.reg8 = REG8_E}, {.reg8 = REG8_B}}},
    {{ld_r_rp}, {{.reg8 = REG8_E}, {.reg8 = REG8_C}}},
    {{ld_r_rp}, {{.reg8 = REG8_E}, {.reg8 = REG8_D}}},
    {{ld_r_rp}, {{.reg8 = REG8_E}, {.reg8 = REG8_E}}},
    {{ld_r_rp}, {{.reg8 = REG8_E}, {.reg8 = REG8_H}}},
    {{ld_r_rp}, {{.reg8 = REG8_E}, {.reg8 = REG8_L}}},
    {{ld_r_hl_m0, ld_r_hl_m1}, {{.reg8 = REG8_E}}},
    {{ld_r_rp}, {{.reg8 = REG8_E}, {.reg8 = REG8_A}}},
    {{ld_r_rp}, {{.reg8 = REG8_H}, {.reg8 = REG8_B}}},
    {{ld_r_rp}, {{.reg8 = REG8_H}, {.reg8 = REG8_C}}},
    {{ld_r_rp}, {{.reg8 = REG8_H}, {.reg8 = REG8_D}}},
    {{ld_r_rp}, {{.reg8 = REG8_H}, {.reg8 = REG8_E}}},
    {{ld_r_rp}, {{.reg8 = REG8_H}, {.reg8 = REG8_H}}},
    {{ld_r_rp}, {{.reg8 = REG8_H}, {.reg8 = REG8_L}}},
    {{ld_r_hl_m0, ld_r_hl_m1}, {{.reg8 = REG8_H}}},
    {{ld_r_rp}, {{.reg8 = REG8_H}, {.reg8 = REG8_A}}},
    {{ld_r_rp}, {{.reg8 = REG8_L}, {.reg8 = REG8_B}}},
    {{ld_r_rp}, {{.reg8 = REG8_L}, {.reg8 = REG8_C}}},
    {{ld_r_rp}, {{.reg8 = REG8_L}, {.reg8 = REG8_D}}},
    {{ld_r_rp}, {{.reg8 = REG8_L}, {.reg8 = REG8_E}}},
    {{ld_r_rp}, {{.reg8 = REG8_L}, {.reg8 = REG8_H}}},
    {{ld_r_rp}, {{.reg8 = REG8_L}, {.reg8 = REG8_L}}},
    {{ld_r_hl_m0, ld_r_hl_m1}, {{.reg8 = REG8_L}}},
    {{ld_r_rp}, {{.reg8 = REG8_L}, {.reg8 = REG8_A}}},
    {{ld_hl_r_m0, ld_hl_r_m1}, {{.reg8 = REG8_B}}},
    {{ld_hl_r_m0, ld_hl_r_m1}, {{.reg8 = REG8_C}}},
    {{ld_hl_r_m0, ld_hl_r_m1}, {{.reg8 = REG8_D}}},
    {{ld_hl_r_m0, ld_hl_r_m1}, {{.reg8 = REG8_E}}},
    {{ld_hl_r_m0, ld_hl_r_m1}, {{.reg8 = REG8_H}}},
    {{ld_hl_r_m0, ld_hl_r_m1}, {{.reg8 = REG8_L}}},
    {{halt}, {}},
    {{ld_hl_r_m0, ld_hl_r_m1}, {{.reg8 = REG8_A}}},
    {{ld_r_rp}, {{.reg8 = REG8_A}, {.reg8 = REG8_B}}},
    {{ld_r_rp}, {{.reg8 = REG8_A}, {.reg8 = REG8_C}}},
    {{ld_r_rp}, {{.reg8 = REG8_A}, {.reg8 = REG8_D}}},
    {{ld_r_rp}, {{.reg8 = REG8_A}, {.reg8 = REG8_E}}},
    {{ld_r_rp}, {{.reg8 = REG8_A}, {.reg8 = REG8_H}}},
    {{ld_r_rp}, {{.reg8 = REG8_A}, {.reg8 = REG8_L}}},
    {{ld_r_hl_m0, ld_r_hl_m1}, {{.reg8 = REG8_A}}},
    {{ld_r_rp}, {{.reg8 = REG8_A}, {.reg8 = REG8_A}}},
    {{add_r}, {{.reg8 = REG8_B}}},
    {{add_r}, {{.reg8 = REG8_C}}},
    {{add_r}, {{.reg8 = REG8_D}}},
    {{add_r}, {{.reg8 = REG8_E}}},
    {{add_r}, {{.reg8 = REG8_H}}},
    {{add_r}, {{.reg8 = REG8_L}}},
    {{add_hl_m0, add_hl_m1}, {}},
    {{add_r}, {{.reg8 = REG8_A}}},
    {{adc_r}, {{.reg8 = REG8_B}}},
    {{adc_r}, {{.reg8 = REG8_C}}},
    {{adc_r}, {{.reg8 = REG8_D}}},
    {{adc_r}, {{.reg8 = REG8_E}}},
    {{adc_r}, {{.reg8 = REG8_H}}},
    {{adc_r}, {{.reg8 = REG8_L}}},
    {{adc_hl_m0, adc_hl_m1}, {}},
    {{adc_r}, {{.reg8 = REG8_A}}},
    {{sub_r}, {{.reg8 = REG8_B}}},
    {{sub_r}, {{.reg8 = REG8_C}}},
    {{sub_r}, {{.reg8 = REG8_D}}},
    {{sub_r}, {{.reg8 = REG8_E}}},
    {{sub_r}, {{.reg8 = REG8_H}}},
    {{sub_r}, {{.reg8 = REG8_L}}},
    {{sub_hl_m0, sub_hl_m1}, {}},
    {{sub_r}, {{.reg8 = REG8_A}}},
    {{sbc_r}, {{.reg8 = REG8_B}}},
    {{sbc_r}, {{.reg8 = REG8_C}}},
    {{sbc_r}, {{.reg8 = REG8_D}}},
    {{sbc_r}, {{.reg8 = REG8_E}}},
    {{sbc_r}, {{.reg8 = REG8_H}}},
    {{sbc_r}, {{.reg8 = REG8_L}}},
    {{sbc_hl_m0, sbc_hl_m1}, {}},
    {{sbc_r}, {{.reg8 = REG8_A}}},
    {{and_r}, {{.reg8 = REG8_B}}},
    {{and_r}, {{.reg8 = REG8_C}}},
    {{and_r}, {{.reg8 = REG8_D}}},
    {{and_r}, {{.reg8 = REG8_E}}},
    {{and_r}, {{.reg8 = REG8_H}}},
    {{and_r}, {{.reg8 = REG8_L}}},
    {{and_hl_m0, and_hl_m1}, {}},
    {{and_r}, {{.reg8 = REG8_A}}},
    {{xor_r}, {{.reg8 = REG8_B}}},
    {{xor_r}, {{.reg8 = REG8_C}}},
    {{xor_r}, {{.reg8 = REG8_D}}},
    {{xor_r}, {{.reg8 = REG8_E}}},
    {{xor_r}, {{.reg8 = REG8_H}}},
    {{xor_r}, {{.reg8 = REG8_L}}},
    {{xor_hl_m0, xor_hl_m1}, {}},
    {{xor_r}, {{.reg8 = REG8_A}}},
    {{or_r}, {{.reg8 = REG8_B}}},
    {{or_r}, {{.reg8 = REG8_C}}},
    {{or_r}, {{.reg8 = REG8_D}}},
    {{or_r}, {{.reg8 = REG8_E}}},
    {{or_r}, {{.reg8 = REG8_H}}},
    {{or_r}, {{.reg8 = REG8_L}}},
    {{or_hl_m0, or_hl_m1}, {}},
    {{or_r}, {{.reg8 = REG8_A}}},
    {{cp_r}, {{.reg8 = REG8_B}}},
    {{cp_r}, {{.reg8 = REG8_C}}},
    {{cp_r}, {{.reg8 = REG8_D}}},
    {{cp_r}, {{.reg8 = REG8_E}}},
    {{cp_r}, {{.reg8 = REG8_H}}},
    {{cp_r}, {{.reg8 = REG8_L}}},
    {{cp_hl_m0, cp_hl_m1}, {}},
    {{cp_r}, {{.reg8 = REG8_A}}},
    {{ret_ncc_m0, ret_ncc_m1, ret_ncc_m2, ret_ncc_m3, ret_ncc_m4}, {{.flags = ZERO_FLAG}}},
    {{pop_rr_m0, pop_rr_m1, pop_rr_m2}, {{.reg16 = REG16_BC}}},
    {{jp_ncc_nn_m0, jp_ncc_nn_m1, jp_ncc_nn_m2, jp_ncc_nn_m3}, {{.flags = ZERO_FLAG}}},
    {{jp_nn_m0, jp_nn_m1, jp_nn_m2, jp_nn_m3}, {}},
    {{call_ncc_nn_m0, call_ncc_nn_m1, call_ncc_nn_m2, call_ncc_nn_m3, call_ncc_nn_m4, call_ncc_nn_m5}, {{.flags = ZERO_FLAG}}},
    {{push_rr_m0, push_rr_m1, push_rr_m2, push_rr_m3}, {{.reg16 = REG16_BC}}},
    {{add_n_m0, add_n_m1}, {}},
    {{rst_n_m0, rst_n_m1, rst_n_m2, rst_n_m3}, {{.data = 0x00}}},
    {{ret_cc_m0, ret_cc_m1, ret_cc_m2, ret_cc_m3, ret_cc_m4}, {{.flags = ZERO_FLAG}}},
    {{ret_m0, ret_m1, ret_m2, ret_m3}, {}},
    {{jp_cc_nn_m0, jp_cc_nn_m1, jp_cc_nn_m2, jp_cc_nn_m3}, {{.flags = ZERO_FLAG}}},
    {{cb_fetch}, {}},
    {{call_cc_nn_m0, call_cc_nn_m1, call_cc_nn_m2, call_cc_nn_m3, call_cc_nn_m4, call_ncc_nn_m5}, {{.flags = ZERO_FLAG}}},
    {{call_nn_m0, call_nn_m1, call_nn_m2, call_nn_m3, call_nn_m4, call_nn_m5}, {}},
    {{adc_n_m0, adc_n_m1}, {}},
    {{rst_n_m0, rst_n_m1, rst_n_m2, rst_n_m3}, {{.data = 0x08}}},
    {{ret_ncc_m0, ret_ncc_m1, ret_ncc_m2, ret_ncc_m3, ret_ncc_m4}, {{.flags = CARRY_FLAG}}},
    {{pop_rr_m0, pop_rr_m1, pop_rr_m2}, {{.reg16 = REG16_DE}}},
    {{jp_ncc_nn_m0, jp_ncc_nn_m1, jp_ncc_nn_m2, jp_ncc_nn_m3}, {{.flags = CARRY_FLAG}}},
    {{unimplemented_instruction}, {}},
    {{call_ncc_nn_m0, call_ncc_nn_m1, call_ncc_nn_m2, call_ncc_nn_m3, call_ncc_nn_m4, call_ncc_nn_m5}, {{.flags = CARRY_FLAG}}},
    {{push_rr_m0, push_rr_m1, push_rr_m2, push_rr_m3}, {{.reg16 = REG16_DE}}},
    {{sub_n_m0, sub_n_m1}, {}},
    {{rst_n_m0, rst_n_m1, rst_n_m2, rst_n_m3}, {{.data = 0x10}}},
    {{ret_cc_m0, ret_cc_m1, ret_cc_m2, ret_cc_m3, ret_cc_m4}, {{.flags = CARRY_FLAG}}},
    {{reti_m0, reti_m1, reti_m2, reti_m3}, {}},
    {{jp_cc_nn_m0, jp_cc_nn_m1, jp_cc_nn_m2, jp_cc_nn_m3}, {{.flags = CARRY_FLAG}}},
    {{unimplemented_instruction}, {}},
    {{call_cc_nn_m0, call_cc_nn_m1, call_cc_nn_m2, call_cc_nn_m3, call_cc_nn_m4, call_cc_nn_m5}, {{.flags = CARRY_FLAG}}},
    {{unimplemented_instruction}, {}},
    {{sbc_n_m0, sbc_n_m1}, {}},
    {{rst_n_m0, rst_n_m1, rst_n_m2, rst_n_m3}, {{.data = 0x18}}},
    {{ldh_n_a_m0, ldh_n_a_m1, ldh_n_a_m2}, {}},
    {{pop_rr_m0, pop_rr_m1, pop_rr_m2}, {{.reg16 = REG16_HL}}},
    {{ldh_c_a_m0, ldh_c_a_m1}, {}},
    {{unimplemented_instruction}, {}},
    {{unimplemented_instruction}, {}},
    {{push_rr_m0, push_rr_m1, push_rr_m2, push_rr_m3}, {{.reg16 = REG16_HL}}},
    {{and_n_m0, and_n_m1}, {}},
    {{rst_n_m0, rst_n_m1, rst_n_m2, rst_n_m3}, {{.data = 0x20}}},
    {{add_sp_e_m0, add_sp_e_m1, add_sp_e_m2, add_sp_e_m3}, {}},
    {{jp_hl}, {}},
    {{ld_nn_a_m0, ld_nn_a_m1, ld_nn_a_m2, ld_nn_a_m3}, {}},
    {{unimplemented_instruction}, {}},
    {{unimplemented_instruction}, {}},
    {{unimplemented_instruction}, {}},
    {{xor_n_m0, xor_n_m1}, {}},
    {{rst_n_m0, rst_n_m1, rst_n_m2, rst_n_m3}, {{.data = 0x28}}},
    {{ldh_a_n_m0, ldh_a_n_m1, ldh_a_n_m2}, {}},
    {{pop_rr_m0, pop_rr_m1, pop_rr_m2}, {{.reg16 = REG16_AF}}},
    {{ldh_a_c_m0, ldh_a_c_m1}, {}},
    {{di}, {}},
    {{unimplemented_instruction}, {}},
    {{push_rr_m0, push_rr_m1, push_rr_m2, push_rr_m3}, {{.reg16 = REG16_AF}}},
    {{or_n_m0, or_n_m1}, {}},
    {{rst_n_m0, rst_n_m1, rst_n_m2, rst_n_m3}, {{.data = 0x30}}},
    {{ld_hl_spe_m0, ld_hl_spe_m1, ld_hl_spe_m2}, {}},
    {{ld_sp_hl_m0, ld_sp_hl_m1}, {}},
    {{ld_a_nn_m0, ld_a_nn_m1, ld_a_nn_m2, ld_a_nn_m3}, {}},
    {{ei}, {}},
    {{unimplemented_instruction}, {}},
    {{unimplemented_instruction}, {}},
    {{cp_n_m0, cp_n_m1}, {}},
    {{rst_n_m0, rst_n_m1, rst_n_m2, rst_n_m3}, {{.data = 0x38}}},
};

Instruction cb_instructions[] = {
    {{rlc_r}, {{.reg8 = REG8_B}}},
    {{rlc_r}, {{.reg8 = REG8_C}}},
    {{rlc_r}, {{.reg8 = REG8_D}}},
    {{rlc_r}, {{.reg8 = REG8_E}}},
    {{rlc_r}, {{.reg8 = REG8_H}}},
    {{rlc_r}, {{.reg8 = REG8_L}}},
    {{rlc_hl_m0, rlc_hl_m1, rlc_hl_m2}, {}},
    {{rlc_r}, {{.reg8 = REG8_A}}},
    {{rrc_r}, {{.reg8 = REG8_B}}},
    {{rrc_r}, {{.reg8 = REG8_C}}},
    {{rrc_r}, {{.reg8 = REG8_D}}},
    {{rrc_r}, {{.reg8 = REG8_E}}},
    {{rrc_r}, {{.reg8 = REG8_H}}},
    {{rrc_r}, {{.reg8 = REG8_L}}},
    {{rrc_hl_m0, rrc_hl_m1, rrc_hl_m2}, {}},
    {{rrc_r}, {{.reg8 = REG8_A}}},
    {{rl_r}, {{.reg8 = REG8_B}}},
    {{rl_r}, {{.reg8 = REG8_C}}},
    {{rl_r}, {{.reg8 = REG8_D}}},
    {{rl_r}, {{.reg8 = REG8_E}}},
    {{rl_r}, {{.reg8 = REG8_H}}},
    {{rl_r}, {{.reg8 = REG8_L}}},
    {{rl_hl_m0, rl_hl_m1, rl_hl_m2}, {}},
    {{rl_r}, {{.reg8 = REG8_A}}},
    {{rr_r}, {{.reg8 = REG8_B}}},
    {{rr_r}, {{.reg8 = REG8_C}}},
    {{rr_r}, {{.reg8 = REG8_D}}},
    {{rr_r}, {{.reg8 = REG8_E}}},
    {{rr_r}, {{.reg8 = REG8_H}}},
    {{rr_r}, {{.reg8 = REG8_L}}},
    {{rr_hl_m0, rr_hl_m1, rr_hl_m2}, {}},
    {{rr_r}, {{.reg8 = REG8_A}}},
    {{sla_r}, {{.reg8 = REG8_B}}},
    {{sla_r}, {{.reg8 = REG8_C}}},
    {{sla_r}, {{.reg8 = REG8_D}}},
    {{sla_r}, {{.reg8 = REG8_E}}},
    {{sla_r}, {{.reg8 = REG8_H}}},
    {{sla_r}, {{.reg8 = REG8_L}}},
    {{sla_hl_m0, sla_hl_m1, sla_hl_m2}, {}},
    {{sla_r}, {{.reg8 = REG8_A}}},
    {{sra_r}, {{.reg8 = REG8_B}}},
    {{sra_r}, {{.reg8 = REG8_C}}},
    {{sra_r}, {{.reg8 = REG8_D}}},
    {{sra_r}, {{.reg8 = REG8_E}}},
    {{sra_r}, {{.reg8 = REG8_H}}},
    {{sra_r}, {{.reg8 = REG8_L}}},
    {{sra_hl_m0, sra_hl_m1, sra_hl_m2}, {}},
    {{sra_r}, {{.reg8 = REG8_A}}},
    {{swap_r}, {{.reg8 = REG8_B}}},
    {{swap_r}, {{.reg8 = REG8_C}}},
    {{swap_r}, {{.reg8 = REG8_D}}},
    {{swap_r}, {{.reg8 = REG8_E}}},
    {{swap_r}, {{.reg8 = REG8_H}}},
    {{swap_r}, {{.reg8 = REG8_L}}},
    {{swap_hl_m0, swap_hl_m1, swap_hl_m2}, {}},
    {{swap_r}, {{.reg8 = REG8_A}}},
    {{srl_r}, {{.reg8 = REG8_B}}},
    {{srl_r}, {{.reg8 = REG8_C}}},
    {{srl_r}, {{.reg8 = REG8_D}}},
    {{srl_r}, {{.reg8 = REG8_E}}},
    {{srl_r}, {{.reg8 = REG8_H}}},
    {{srl_r}, {{.reg8 = REG8_L}}},
    {{srl_hl_m0, srl_hl_m1, srl_hl_m2}, {}},
    {{srl_r}, {{.reg8 = REG8_A}}},
    {{bit_b_r}, {{.data = 0x01}, {.reg8 = REG8_B}}},
    {{bit_b_r}, {{.data = 0x01}, {.reg8 = REG8_C}}},
    {{bit_b_r}, {{.data = 0x01}, {.reg8 = REG8_D}}},
    {{bit_b_r}, {{.data = 0x01}, {.reg8 = REG8_E}}},
    {{bit_b_r}, {{.data = 0x01}, {.reg8 = REG8_H}}},
    {{bit_b_r}, {{.data = 0x01}, {.reg8 = REG8_L}}},
    {{bit_b_hl_m0, bit_b_hl_m1}, {{.data = 0x01}}},
    {{bit_b_r}, {{.data = 0x01}, {.reg8 = REG8_A}}},
    {{bit_b_r}, {{.data = 0x02}, {.reg8 = REG8_B}}},
    {{bit_b_r}, {{.data = 0x02}, {.reg8 = REG8_C}}},
    {{bit_b_r}, {{.data = 0x02}, {.reg8 = REG8_D}}},
    {{bit_b_r}, {{.data = 0x02}, {.reg8 = REG8_E}}},
    {{bit_b_r}, {{.data = 0x02}, {.reg8 = REG8_H}}},
    {{bit_b_r}, {{.data = 0x02}, {.reg8 = REG8_L}}},
    {{bit_b_hl_m0, bit_b_hl_m1}, {{.data = 0x02}}},
    {{bit_b_r}, {{.data = 0x02}, {.reg8 = REG8_A}}},
    {{bit_b_r}, {{.data = 0x04}, {.reg8 = REG8_B}}},
    {{bit_b_r}, {{.data = 0x04}, {.reg8 = REG8_C}}},
    {{bit_b_r}, {{.data = 0x04}, {.reg8 = REG8_D}}},
    {{bit_b_r}, {{.data = 0x04}, {.reg8 = REG8_E}}},
    {{bit_b_r}, {{.data = 0x04}, {.reg8 = REG8_H}}},
    {{bit_b_r}, {{.data = 0x04}, {.reg8 = REG8_L}}},
    {{bit_b_hl_m0, bit_b_hl_m1}, {{.data = 0x04}}},
    {{bit_b_r}, {{.data = 0x04}, {.reg8 = REG8_A}}},
    {{bit_b_r}, {{.data = 0x08}, {.reg8 = REG8_B}}},
    {{bit_b_r}, {{.data = 0x08}, {.reg8 = REG8_C}}},
    {{bit_b_r}, {{.data = 0x08}, {.reg8 = REG8_D}}},
    {{bit_b_r}, {{.data = 0x08}, {.reg8 = REG8_E}}},
    {{bit_b_r}, {{.data = 0x08}, {.reg8 = REG8_H}}},
    {{bit_b_r}, {{.data = 0x08}, {.reg8 = REG8_L}}},
    {{bit_b_hl_m0, bit_b_hl_m1}, {{.data = 0x08}}},
    {{bit_b_r}, {{.data = 0x08}, {.reg8 = REG8_A}}},
    {{bit_b_r}, {{.data = 0x10}, {.reg8 = REG8_B}}},
    {{bit_b_r}, {{.data = 0x10}, {.reg8 = REG8_C}}},
    {{bit_b_r}, {{.data = 0x10}, {.reg8 = REG8_D}}},
    {{bit_b_r}, {{.data = 0x10}, {.reg8 = REG8_E}}},
    {{bit_b_r}, {{.data = 0x10}, {.reg8 = REG8_H}}},
    {{bit_b_r}, {{.data = 0x10}, {.reg8 = REG8_L}}},
    {{bit_b_hl_m0, bit_b_hl_m1}, {{.data = 0x10}}},
    {{bit_b_r}, {{.data = 0x10}, {.reg8 = REG8_A}}},
    {{bit_b_r}, {{.data = 0x20}, {.reg8 = REG8_B}}},
    {{bit_b_r}, {{.data = 0x20}, {.reg8 = REG8_C}}},
    {{bit_b_r}, {{.data = 0x20}, {.reg8 = REG8_D}}},
    {{bit_b_r}, {{.data = 0x20}, {.reg8 = REG8_E}}},
    {{bit_b_r}, {{.data = 0x20}, {.reg8 = REG8_H}}},
    {{bit_b_r}, {{.data = 0x20}, {.reg8 = REG8_L}}},
    {{bit_b_hl_m0, bit_b_hl_m1}, {{.data = 0x20}}},
    {{bit_b_r}, {{.data = 0x20}, {.reg8 = REG8_A}}},
    {{bit_b_r}, {{.data = 0x40}, {.reg8 = REG8_B}}},
    {{bit_b_r}, {{.data = 0x40}, {.reg8 = REG8_C}}},
    {{bit_b_r}, {{.data = 0x40}, {.reg8 = REG8_D}}},
    {{bit_b_r}, {{.data = 0x40}, {.reg8 = REG8_E}}},
    {{bit_b_r}, {{.data = 0x40}, {.reg8 = REG8_H}}},
    {{bit_b_r}, {{.data = 0x40}, {.reg8 = REG8_L}}},
    {{bit_b_hl_m0, bit_b_hl_m1}, {{.data = 0x40}}},
    {{bit_b_r}, {{.data = 0x40}, {.reg8 = REG8_A}}},
    {{bit_b_r}, {{.data = 0x80}, {.reg8 = REG8_B}}},
    {{bit_b_r}, {{.data = 0x80}, {.reg8 = REG8_C}}},
    {{bit_b_r}, {{.data = 0x80}, {.reg8 = REG8_D}}},
    {{bit_b_r}, {{.data = 0x80}, {.reg8 = REG8_E}}},
    {{bit_b_r}, {{.data = 0x80}, {.reg8 = REG8_H}}},
    {{bit_b_r}, {{.data = 0x80}, {.reg8 = REG8_L}}},
    {{bit_b_hl_m0, bit_b_hl_m1}, {{.data = 0x80}}},
    {{bit_b_r}, {{.data = 0x80}, {.reg8 = REG8_A}}},
    {{res_b_r}, {{.data = 0x01}, {.reg8 = REG8_B}}},
    {{res_b_r}, {{.data = 0x01}, {.reg8 = REG8_C}}},
    {{res_b_r}, {{.data = 0x01}, {.reg8 = REG8_D}}},
    {{res_b_r}, {{.data = 0x01}, {.reg8 = REG8_E}}},
    {{res_b_r}, {{.data = 0x01}, {.reg8 = REG8_H}}},
    {{res_b_r}, {{.data = 0x01}, {.reg8 = REG8_L}}},
    {{res_b_hl_m0, res_b_hl_m1, res_b_hl_m2}, {{.data = 0x01}}},
    {{res_b_r}, {{.data = 0x01}, {.reg8 = REG8_A}}},
    {{res_b_r}, {{.data = 0x02}, {.reg8 = REG8_B}}},
    {{res_b_r}, {{.data = 0x02}, {.reg8 = REG8_C}}},
    {{res_b_r}, {{.data = 0x02}, {.reg8 = REG8_D}}},
    {{res_b_r}, {{.data = 0x02}, {.reg8 = REG8_E}}},
    {{res_b_r}, {{.data = 0x02}, {.reg8 = REG8_H}}},
    {{res_b_r}, {{.data = 0x02}, {.reg8 = REG8_L}}},
    {{res_b_hl_m0, res_b_hl_m1, res_b_hl_m2}, {{.data = 0x02}}},
    {{res_b_r}, {{.data = 0x02}, {.reg8 = REG8_A}}},
    {{res_b_r}, {{.data = 0x04}, {.reg8 = REG8_B}}},
    {{res_b_r}, {{.data = 0x04}, {.reg8 = REG8_C}}},
    {{res_b_r}, {{.data = 0x04}, {.reg8 = REG8_D}}},
    {{res_b_r}, {{.data = 0x04}, {.reg8 = REG8_E}}},
    {{res_b_r}, {{.data = 0x04}, {.reg8 = REG8_H}}},
    {{res_b_r}, {{.data = 0x04}, {.reg8 = REG8_L}}},
    {{res_b_hl_m0, res_b_hl_m1, res_b_hl_m2}, {{.data = 0x04}}},
    {{res_b_r}, {{.data = 0x04}, {.reg8 = REG8_A}}},
    {{res_b_r}, {{.data = 0x08}, {.reg8 = REG8_B}}},
    {{res_b_r}, {{.data = 0x08}, {.reg8 = REG8_C}}},
    {{res_b_r}, {{.data = 0x08}, {.reg8 = REG8_D}}},
    {{res_b_r}, {{.data = 0x08}, {.reg8 = REG8_E}}},
    {{res_b_r}, {{.data = 0x08}, {.reg8 = REG8_H}}},
    {{res_b_r}, {{.data = 0x08}, {.reg8 = REG8_L}}},
    {{res_b_hl_m0, res_b_hl_m1, res_b_hl_m2}, {{.data = 0x08}}},
    {{res_b_r}, {{.data = 0x08}, {.reg8 = REG8_A}}},
    {{res_b_r}, {{.data = 0x10}, {.reg8 = REG8_B}}},
    {{res_b_r}, {{.data = 0x10}, {.reg8 = REG8_C}}},
    {{res_b_r}, {{.data = 0x10}, {.reg8 = REG8_D}}},
    {{res_b_r}, {{.data = 0x10}, {.reg8 = REG8_E}}},
    {{res_b_r}, {{.data = 0x10}, {.reg8 = REG8_H}}},
    {{res_b_r}, {{.data = 0x10}, {.reg8 = REG8_L}}},
    {{res_b_hl_m0, res_b_hl_m1, res_b_hl_m2}, {{.data = 0x10}}},
    {{res_b_r}, {{.data = 0x10}, {.reg8 = REG8_A}}},
    {{res_b_r}, {{.data = 0x20}, {.reg8 = REG8_B}}},
    {{res_b_r}, {{.data = 0x20}, {.reg8 = REG8_C}}},
    {{res_b_r}, {{.data = 0x20}, {.reg8 = REG8_D}}},
    {{res_b_r}, {{.data = 0x20}, {.reg8 = REG8_E}}},
    {{res_b_r}, {{.data = 0x20}, {.reg8 = REG8_H}}},
    {{res_b_r}, {{.data = 0x20}, {.reg8 = REG8_L}}},
    {{res_b_hl_m0, res_b_hl_m1, res_b_hl_m2}, {{.data = 0x20}}},
    {{res_b_r}, {{.data = 0x20}, {.reg8 = REG8_A}}},
    {{res_b_r}, {{.data = 0x40}, {.reg8 = REG8_B}}},
    {{res_b_r}, {{.data = 0x40}, {.reg8 = REG8_C}}},
    {{res_b_r}, {{.data = 0x40}, {.reg8 = REG8_D}}},
    {{res_b_r}, {{.data = 0x40}, {.reg8 = REG8_E}}},
    {{res_b_r}, {{.data = 0x40}, {.reg8 = REG8_H}}},
    {{res_b_r}, {{.data = 0x40}, {.reg8 = REG8_L}}},
    {{res_b_hl_m0, res_b_hl_m1, res_b_hl_m2}, {{.data = 0x40}}},
    {{res_b_r}, {{.data = 0x40}, {.reg8 = REG8_A}}},
    {{res_b_r}, {{.data = 0x80}, {.reg8 = REG8_B}}},
    {{res_b_r}, {{.data = 0x80}, {.reg8 = REG8_C}}},
    {{res_b_r}, {{.data = 0x80}, {.reg8 = REG8_D}}},
    {{res_b_r}, {{.data = 0x80}, {.reg8 = REG8_E}}},
    {{res_b_r}, {{.data = 0x80}, {.reg8 = REG8_H}}},
    {{res_b_r}, {{.data = 0x80}, {.reg8 = REG8_L}}},
    {{res_b_hl_m0, res_b_hl_m1, res_b_hl_m2}, {{.data = 0x80}}},
    {{res_b_r}, {{.data = 0x80}, {.reg8 = REG8_A}}},
    {{set_b_r}, {{.data = 0x01}, {.reg8 = REG8_B}}},
    {{set_b_r}, {{.data = 0x01}, {.reg8 = REG8_C}}},
    {{set_b_r}, {{.data = 0x01}, {.reg8 = REG8_D}}},
    {{set_b_r}, {{.data = 0x01}, {.reg8 = REG8_E}}},
    {{set_b_r}, {{.data = 0x01}, {.reg8 = REG8_H}}},
    {{set_b_r}, {{.data = 0x01}, {.reg8 = REG8_L}}},
    {{set_b_hl_m0, set_b_hl_m1, set_b_hl_m2}, {{.data = 0x01}}},
    {{set_b_r}, {{.data = 0x01}, {.reg8 = REG8_A}}},
    {{set_b_r}, {{.data = 0x02}, {.reg8 = REG8_B}}},
    {{set_b_r}, {{.data = 0x02}, {.reg8 = REG8_C}}},
    {{set_b_r}, {{.data = 0x02}, {.reg8 = REG8_D}}},
    {{set_b_r}, {{.data = 0x02}, {.reg8 = REG8_E}}},
    {{set_b_r}, {{.data = 0x02}, {.reg8 = REG8_H}}},
    {{set_b_r}, {{.data = 0x02}, {.reg8 = REG8_L}}},
    {{set_b_hl_m0, set_b_hl_m1, set_b_hl_m2}, {{.data = 0x02}}},
    {{set_b_r}, {{.data = 0x02}, {.reg8 = REG8_A}}},
    {{set_b_r}, {{.data = 0x04}, {.reg8 = REG8_B}}},
    {{set_b_r}, {{.data = 0x04}, {.reg8 = REG8_C}}},
    {{set_b_r}, {{.data = 0x04}, {.reg8 = REG8_D}}},
    {{set_b_r}, {{.data = 0x04}, {.reg8 = REG8_E}}},
    {{set_b_r}, {{.data = 0x04}, {.reg8 = REG8_H}}},
    {{set_b_r}, {{.data = 0x04}, {.reg8 = REG8_L}}},
    {{set_b_hl_m0, set_b_hl_m1, set_b_hl_m2}, {{.data = 0x04}}},
    {{set_b_r}, {{.data = 0x04}, {.reg8 = REG8_A}}},
    {{set_b_r}, {{.data = 0x08}, {.reg8 = REG8_B}}},
    {{set_b_r}, {{.data = 0x08}, {.reg8 = REG8_C}}},
    {{set_b_r}, {{.data = 0x08}, {.reg8 = REG8_D}}},
    {{set_b_r}, {{.data = 0x08}, {.reg8 = REG8_E}}},
    {{set_b_r}, {{.data = 0x08}, {.reg8 = REG8_H}}},
    {{set_b_r}, {{.data = 0x08}, {.reg8 = REG8_L}}},
    {{set_b_hl_m0, set_b_hl_m1, set_b_hl_m2}, {{.data = 0x08}}},
    {{set_b_r}, {{.data = 0x08}, {.reg8 = REG8_A}}},
    {{set_b_r}, {{.data = 0x10}, {.reg8 = REG8_B}}},
    {{set_b_r}, {{.data = 0x10}, {.reg8 = REG8_C}}},
    {{set_b_r}, {{.data = 0x10}, {.reg8 = REG8_D}}},
    {{set_b_r}, {{.data = 0x10}, {.reg8 = REG8_E}}},
    {{set_b_r}, {{.data = 0x10}, {.reg8 = REG8_H}}},
    {{set_b_r}, {{.data = 0x10}, {.reg8 = REG8_L}}},
    {{set_b_hl_m0, set_b_hl_m1, set_b_hl_m2}, {{.data = 0x10}}},
    {{set_b_r}, {{.data = 0x10}, {.reg8 = REG8_A}}},
    {{set_b_r}, {{.data = 0x20}, {.reg8 = REG8_B}}},
    {{set_b_r}, {{.data = 0x20}, {.reg8 = REG8_C}}},
    {{set_b_r}, {{.data = 0x20}, {.reg8 = REG8_D}}},
    {{set_b_r}, {{.data = 0x20}, {.reg8 = REG8_E}}},
    {{set_b_r}, {{.data = 0x20}, {.reg8 = REG8_H}}},
    {{set_b_r}, {{.data = 0x20}, {.reg8 = REG8_L}}},
    {{set_b_hl_m0, set_b_hl_m1, set_b_hl_m2}, {{.data = 0x20}}},
    {{set_b_r}, {{.data = 0x20}, {.reg8 = REG8_A}}},
    {{set_b_r}, {{.data = 0x40}, {.reg8 = REG8_B}}},
    {{set_b_r}, {{.data = 0x40}, {.reg8 = REG8_C}}},
    {{set_b_r}, {{.data = 0x40}, {.reg8 = REG8_D}}},
    {{set_b_r}, {{.data = 0x40}, {.reg8 = REG8_E}}},
    {{set_b_r}, {{.data = 0x40}, {.reg8 = REG8_H}}},
    {{set_b_r}, {{.data = 0x40}, {.reg8 = REG8_L}}},
    {{set_b_hl_m0, set_b_hl_m1, set_b_hl_m2}, {{.data = 0x40}}},
    {{set_b_r}, {{.data = 0x40}, {.reg8 = REG8_A}}},
    {{set_b_r}, {{.data = 0x80}, {.reg8 = REG8_B}}},
    {{set_b_r}, {{.data = 0x80}, {.reg8 = REG8_C}}},
    {{set_b_r}, {{.data = 0x80}, {.reg8 = REG8_D}}},
    {{set_b_r}, {{.data = 0x80}, {.reg8 = REG8_E}}},
    {{set_b_r}, {{.data = 0x80}, {.reg8 = REG8_H}}},
    {{set_b_r}, {{.data = 0x80}, {.reg8 = REG8_L}}},
    {{set_b_hl_m0, set_b_hl_m1, set_b_hl_m2}, {{.data = 0x80}}},
    {{set_b_r}, {{.data = 0x80}, {.reg8 = REG8_A}}},
};

Instruction isr[] =
{
    {{isr_m0, isr_m1, isr_m2, isr_m3, isr_m4}, {}},
};

